config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'complaints#index'
  get 'profile', to: 'pages#profile', as: :profile
  get 'reports', to: 'pages#reports', as: :reports

  resources :complaints, except: :destroy do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :complaints
end

app/models/city.rb
class City < ApplicationRecord
  has_many :complaints
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :complaint
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user # posts a complaint
  belongs_to :category
  belongs_to :city
  validates :description, presence: true
  validates :address, presence: true
  has_many_attached :photos
  has_many :comments, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :complaints
         has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_complaint
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
    flash[:notice] = "You can't like more than once"
  else
    @complaint.comments.create(user_id: current_user.id)
  end
    redirect_to complaint_path(@complaint)
    authorize @complaint
  end

  def destroy
  if !(already_liked?)
    flash[:notice] = "Cannot unlike"
  else
    @comment.destroy
  end
    redirect_to complaint_path(@complaint)
    authorize @complaint
  end

  private
  def find_complaint
    @complaint = Complaint.find(params[:complaint_id])
  end

  def already_liked?
    Comment.where(user_id: current_user.id, complaint_id:
    params[:complaint_id]).exists?
  end

  def find_like
   @comment = @complaint.comments.find(params[:id])
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show, :index, :root]
  before_action :find, only: [:show, :edit]

  def index

    @complaints = Complaint.all
    @complaints = Complaint.geocoded # returns flats with coordinates

    @markers = @complaints.map do |complaint|
      {
        lat: complaint.latitude,
        lng: complaint.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { complaint: complaint })

      }
    end
  end


  def show
    @complaint = Complaint.find(params[:id])
    authorize @complaint
  end

  def new
    @complaint = Complaint.new
    authorize @complaint


  end

  def create
    @complaint = Complaint.new(complaint_params)
    @complaint.user = current_user
    authorize @complaint


    if @complaint.save
      redirect_to root_path, notice: 'Your item was successfully created.'
    else
      render :new
   end
  end

  def edit
    authorize @complaint

  end

  def update
    find
    if @complaint.update(complaint_params)
      authorize @complaint
      redirect_to root_path
    else
      render :edit
    end
  end

 private

  def find
    @complaint = Complaint.find(params[:id])
  end

  def complaint_params
    params.require(:complaint).permit(:category_id, :description, :address, :user_id, :city_id, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @complaint = Complaint.new
    @complaints= Complaint.all
  end

   def index
    @complaint = Complaint.new
    @complaints = complaints.all
  end

  def profile
    @complaints = Complaint.where(user: current_user)
  end

  def reports
    @complaints = Complaint.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/complaints/_info_window.html.erb
<h2><%= complaint.category.name %></h2>
<p><%= complaint.address %></p>
<p><%= complaint.description %></p>
<p><%= complaint.comments.count %> <%= (complaint.comments.count) == 1 ? 'Like' : 'Likes'%></p>

app/views/complaints/index.html.erb
<div class="container">
<div class="header-container">
  <div>
    <a class="image" href="#">
      <%= image_tag "girl.jpg", class: "girl_top" %>
    </a>
  </div>
  <div class="title-container">
    <h1 class="title">Report a Neighborhood Problem</h1>
    <p class="subtitle">Wherever you are</p>
    <%=link_to "Click here to report a problem", new_complaint_path, class:"newcomplaint", id:"button2" %>
  </div>
</div>

 <div class="map-container" id="map"
     style="width: 100%;
     height: 450px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>

app/views/complaints/list.html.erb
<div>
  <h3 class="title-report"> My reports </h3>
</div>

<div class="row justify-content-center">
<% @complaints.each do |complaint| %>
<div class="card card-report" style="width: 18rem;">
  <div class="card-body">

    <h5 class="card-title"><%= complaint.category.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= complaint.address%></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= complaint.city.name%></h6>
    <p class="card-text"><%= complaint.description%></p>
    <a href="#" class="card-link">See Details</a>

  </div>

</div>
<% end %>
</div>

app/views/complaints/new.html.erb
<div class="row _add-complaint">
    <div class="col-5">
      <%= simple_form_for [@complaint] do |f| %>
      <div class="form-inputs">
        <%= f.association :category, input_html: { class: "dropdown" }, include_hidden: false %>
        <%= f.input :description %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
        <%= f.input :address %>
        <%= f.association :city, input_html: { class: "dropdown" }, include_hidden: false %>

        <div class="row d-flex justify-content-between">
          <%= link_to "Cancel", root_path, class: "btn  ml-3 mb-2" %>
        <%= f.submit "Save", class: "btn btn-outline-secondary mr-3 mb-2" %>

        </div>
      </div>


      <% end %>

<!--       < %= link_to "Cancel", root_path, class: "btn-outline-secondary ml-3 mb-2" %>
 -->
    </div>

    <div class="col-1"></div>
    <div class="col-6">
<!--       < %= image_tag "online.svg", class:"mx-auto d-block", alt: "online", width: "80%", id:"online" %>
 -->    </div>
  </div>

app/views/complaints/show.html.erb
<div>
  <div>
    <h3><%= @complaint.category.name %></h3>
  </div>
    <div>
      <% @complaint.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    </div>
      <div>
        <h6 class="card-subtitle mb-2 text-muted"><%= @complaint.address%></h6>
        <h6 class="card-subtitle mb-2 text-muted"><%= @complaint.city.name%></h6>
        <p class="card-text"><%= @complaint.description%></p>

        <% pre_like = @complaint.comments.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
        <%= button_to 'Unlike', complaint_comment_path(@complaint, pre_like), method: :delete %>
        <% else %>
        <%= button_to 'Like', complaint_comments_path(@complaint), method: :post %>
        <% end %>

        <p><%= @complaint.comments.count %> <%= (@complaint.comments.count) == 1 ? 'Like' : 'Likes'%></p>

      </div>
</div>


<div class="backbutton">
  <%= link_to "Back to my reports", profile_path,class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Streetly</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.1/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>

  </head>
  <body>
    <div id="page-container">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div id="content-wrap">

    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    </div>
  </body>
</html>

app/views/pages/profile.html.erb
<div>
  <h3 class="title-report"> My reports </h3>
</div>

<div class="row justify-content-center">
<% @complaints.each do |complaint| %>
<div class="card card-report" style="width: 18rem;">
  <div class="card-body">

    <h5 class="card-title"><%= complaint.category.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= complaint.address%></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= complaint.city.name%></h6>
    <p class="card-text"><%= complaint.description%></p>
    <a class="card-link"> <%= link_to "See details", complaint_path(complaint) %></a>

  </div>

</div>
<% end %>
</div>

app/views/pages/reports.html.erb
<h2>Show reports in your city</h2>

<h3>Select your city </h3>


<div class="row justify-content-center">
<% @complaints.each do |complaint| %>
<div class="card card-report" style="width: 18rem;">
  <div class="card-body">

    <h5 class="card-title"><%= complaint.category.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= complaint.address%></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= complaint.city.name%></h6>
    <p class="card-text"><%= complaint.description%></p>
    <a class="card-link"> <%= link_to "See details", complaint_path(complaint) %></a>

  </div>

</div>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show my-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show my-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-links text-center">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright text-center">
    <strong>Streetly</strong> was made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_map.html.erb
<div id="map"
     style="width: 100%;
     height: 450px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item ">
          <%= link_to "All Reports", reports_path, class: "nav-link reports" %>
        </li>
        <li class="nav-item ">
          <%= link_to "My Profile", profile_path, class: "nav-link profile" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link ", id:"logout" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link button1" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>